services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: invoice_processing_complete
      POSTGRES_USER: gvidzha
      POSTGRES_PASSWORD: supersecretpassword
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://gvidzha:supersecretpassword@db:5432/invoice_processing_complete
    ports:
      - "8000:8000"

  frontend:
    build: ./frontend
    depends_on:
      - backend

  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx_server.conf:/etc/nginx/conf.d/myapp.conf:ro
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - frontend
      - backend

volumes:
  db_data: