"""Complete schema redesign with all template fields

Revision ID: 16b57f469d94
Revises: 59c1c7535aab
Create Date: 2025-08-03 15:29:56.249799

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '16b57f469d94'
down_revision = '59c1c7535aab'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
