"""Add template system extended fields to Invoice model

Revision ID: 23787e755993
Revises: 8929bd8f6134
Create Date: 2025-08-01 23:12:03.274277

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '23787e755993'
down_revision = '8929bd8f6134'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invoices', sa.Column('document_type', sa.String(length=50), nullable=True))
    op.add_column('invoices', sa.Column('document_series', sa.String(length=50), nullable=True))
    op.add_column('invoices', sa.Column('service_delivery_date', sa.DateTime(), nullable=True))
    op.add_column('invoices', sa.Column('contract_number', sa.String(length=100), nullable=True))
    op.add_column('invoices', sa.Column('supplier_vat_payer_number', sa.String(length=50), nullable=True))
    op.add_column('invoices', sa.Column('supplier_vat_number', sa.String(length=50), nullable=True))
    op.add_column('invoices', sa.Column('issue_address', sa.Text(), nullable=True))
    op.add_column('invoices', sa.Column('recipient_vat_number', sa.String(length=50), nullable=True))
    op.add_column('invoices', sa.Column('recipient_bank_name', sa.String(length=255), nullable=True))
    op.add_column('invoices', sa.Column('recipient_account_number', sa.String(length=50), nullable=True))
    op.add_column('invoices', sa.Column('recipient_swift_code', sa.String(length=20), nullable=True))
    op.add_column('invoices', sa.Column('receiving_address', sa.Text(), nullable=True))
    op.add_column('invoices', sa.Column('carrier_name', sa.String(length=255), nullable=True))
    op.add_column('invoices', sa.Column('carrier_vat_number', sa.String(length=50), nullable=True))
    op.add_column('invoices', sa.Column('vehicle_number', sa.String(length=50), nullable=True))
    op.add_column('invoices', sa.Column('driver_name', sa.String(length=255), nullable=True))
    op.add_column('invoices', sa.Column('discount', sa.Float(), nullable=True))
    op.add_column('invoices', sa.Column('total_with_discount', sa.Float(), nullable=True))
    op.add_column('invoices', sa.Column('amount_with_discount', sa.Float(), nullable=True))
    op.add_column('invoices', sa.Column('amount_without_discount', sa.Float(), nullable=True))
    op.add_column('invoices', sa.Column('amount_without_vat', sa.Float(), nullable=True))
    op.add_column('invoices', sa.Column('transaction_type', sa.String(length=100), nullable=True))
    op.add_column('invoices', sa.Column('service_period', sa.String(length=100), nullable=True))
    op.add_column('invoices', sa.Column('payment_method', sa.String(length=100), nullable=True))
    op.add_column('invoices', sa.Column('notes', sa.Text(), nullable=True))
    op.add_column('invoices', sa.Column('issued_by_name', sa.String(length=255), nullable=True))
    op.add_column('invoices', sa.Column('payment_due_date', sa.DateTime(), nullable=True))
    op.add_column('invoices', sa.Column('justification', sa.Text(), nullable=True))
    op.add_column('invoices', sa.Column('total_issued', sa.Float(), nullable=True))
    op.add_column('invoices', sa.Column('weight_kg', sa.Float(), nullable=True))
    op.add_column('invoices', sa.Column('issued_by', sa.String(length=255), nullable=True))
    op.add_column('invoices', sa.Column('total_quantity', sa.Float(), nullable=True))
    op.add_column('invoices', sa.Column('page_number', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('invoices', 'page_number')
    op.drop_column('invoices', 'total_quantity')
    op.drop_column('invoices', 'issued_by')
    op.drop_column('invoices', 'weight_kg')
    op.drop_column('invoices', 'total_issued')
    op.drop_column('invoices', 'justification')
    op.drop_column('invoices', 'payment_due_date')
    op.drop_column('invoices', 'issued_by_name')
    op.drop_column('invoices', 'notes')
    op.drop_column('invoices', 'payment_method')
    op.drop_column('invoices', 'service_period')
    op.drop_column('invoices', 'transaction_type')
    op.drop_column('invoices', 'amount_without_vat')
    op.drop_column('invoices', 'amount_without_discount')
    op.drop_column('invoices', 'amount_with_discount')
    op.drop_column('invoices', 'total_with_discount')
    op.drop_column('invoices', 'discount')
    op.drop_column('invoices', 'driver_name')
    op.drop_column('invoices', 'vehicle_number')
    op.drop_column('invoices', 'carrier_vat_number')
    op.drop_column('invoices', 'carrier_name')
    op.drop_column('invoices', 'receiving_address')
    op.drop_column('invoices', 'recipient_swift_code')
    op.drop_column('invoices', 'recipient_account_number')
    op.drop_column('invoices', 'recipient_bank_name')
    op.drop_column('invoices', 'recipient_vat_number')
    op.drop_column('invoices', 'issue_address')
    op.drop_column('invoices', 'supplier_vat_number')
    op.drop_column('invoices', 'supplier_vat_payer_number')
    op.drop_column('invoices', 'contract_number')
    op.drop_column('invoices', 'service_delivery_date')
    op.drop_column('invoices', 'document_series')
    op.drop_column('invoices', 'document_type')
    # ### end Alembic commands ###
