"""Add supplier bank fields

Revision ID: 59c1c7535aab
Revises: 1d1fdf0b936e
Create Date: 2025-08-03 15:18:28.122448

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '59c1c7535aab'
down_revision = '1d1fdf0b936e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invoices', sa.Column('supplier_bank_name', sa.String(length=255), nullable=True))
    op.add_column('invoices', sa.Column('supplier_swift_code', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('invoices', 'supplier_swift_code')
    op.drop_column('invoices', 'supplier_bank_name')
    # ### end Alembic commands ###
