"""Add complex template fields for supplier banks and products

Revision ID: 5cbbe3ab536c
Revises: 23787e755993
Create Date: 2025-08-01 23:23:28.489834

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5cbbe3ab536c'
down_revision = '23787e755993'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invoices', sa.Column('supplier_banks_json', sa.Text(), nullable=True))
    op.add_column('invoices', sa.Column('product_type', sa.String(length=100), nullable=True))
    op.add_column('invoices', sa.Column('product_items', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('invoices', 'product_items')
    op.drop_column('invoices', 'product_type')
    op.drop_column('invoices', 'supplier_banks_json')
    # ### end Alembic commands ###
