"""Add recipient info and reorganize supplier fields

Revision ID: 8929bd8f6134
Revises: a6cdf4c74ace
Create Date: 2025-08-01 00:24:02.819191

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '8929bd8f6134'
down_revision = 'a6cdf4c74ace'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invoices', sa.Column('supplier_reg_number', sa.String(length=50), nullable=True))
    op.add_column('invoices', sa.Column('supplier_address', sa.Text(), nullable=True))
    op.add_column('invoices', sa.Column('supplier_bank_account', sa.String(length=50), nullable=True))
    op.add_column('invoices', sa.Column('recipient_name', sa.String(length=255), nullable=True))
    op.add_column('invoices', sa.Column('recipient_reg_number', sa.String(length=50), nullable=True))
    op.add_column('invoices', sa.Column('recipient_address', sa.Text(), nullable=True))
    op.add_column('invoices', sa.Column('recipient_bank_account', sa.String(length=50), nullable=True))
    op.add_column('invoices', sa.Column('recipient_confidence', sa.Float(), nullable=True))
    op.add_column('invoices', sa.Column('subtotal_amount', sa.Float(), nullable=True))
    op.drop_column('invoices', 'processing_status')
    op.drop_column('invoices', 'processing_completed_at')
    op.drop_column('invoices', 'address')
    op.drop_column('invoices', 'processing_started_at')
    op.drop_column('invoices', 'bank_account')
    op.drop_column('invoices', 'reg_number')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invoices', sa.Column('reg_number', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('invoices', sa.Column('bank_account', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('invoices', sa.Column('processing_started_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('invoices', sa.Column('address', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('invoices', sa.Column('processing_completed_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('invoices', sa.Column('processing_status', sa.VARCHAR(length=50), server_default=sa.text("'pending'::character varying"), autoincrement=False, nullable=True))
    op.drop_column('invoices', 'subtotal_amount')
    op.drop_column('invoices', 'recipient_confidence')
    op.drop_column('invoices', 'recipient_bank_account')
    op.drop_column('invoices', 'recipient_address')
    op.drop_column('invoices', 'recipient_reg_number')
    op.drop_column('invoices', 'recipient_name')
    op.drop_column('invoices', 'supplier_bank_account')
    op.drop_column('invoices', 'supplier_address')
    op.drop_column('invoices', 'supplier_reg_number')
    # ### end Alembic commands ###
